name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
      - name: Validate JSON
        run: python3 scripts/validate_json.py
